version: "2"

services:
  zeppelin:
    build: ./zeppelin
    image: leftjs/zeppelin:0.8.3
    container_name: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      MASTER: "local[*]"
    ports:
      - 8090:8090
    volumes:
      - ./data:/zeppelin/data
      - ./notebook:/zeppelin/notebook
      - ./logs:/zeppelin/logs
  atlas:
    build: ./atlas
    image: leftjs/atlas:2.0.0
    container_name: atlas
    ports:
      - 21000:21000
networks:
  default:
    external:
      name: sparkcluster_default
